### ISSUE TITLE
Howto properly benchmark NFFT3

### ISSUE THREAD

**Issue by tknopp** [NFFT/NFFT3#13]
Hi, I am currently trying to benchmark NFFT3 against NFFT.jl and am struggling somewhat since the initialization of the plan seems to not include any precomputation. My code looks like this:

https://github.com/tknopp/NFFT.jl/blob/master/test/comparison.jl#L144

When I switch between PRE_PSI and PRE_FULL_PSI there is no effect. The init is less than a millisecond which is much to fast for N=M=1024^2 input. What am I missing?

**Comment by michaelquellmalz** [comment]
The init is mainly doing memory allocation and fftw_init. The time difference should be in the node-dependent precomputation, when setting the nodes `pnfft3.x = Float64.(x)`.

By the way, we noticed that on modern computers there is often barely any benefit from using `PRE_FULL_PSI` or `PRE_LIN_PSI`, so we usually recommend using the flag `PRE_PSI` instead (which is currently not used in comparison.jl, as far as I see).

**Comment by tknopp** [comment]
Ah, thank you very much, I totally forgot that x is not part of the constructor. 

Regarding the precomputation flags I am aware of these things. I try to match what is available in NFFT.jl in order to make things comparable. So I am interested in the question how the performance is under the exact same setting. This helps me identifying bottlenecks in NFFT.jl. So I actually not expect NFFT.jl to be any faster than NFFT3, I just want to know, how much slower we are.

`PRE_FULL_PSI` is a little bit special (and very important for us) since it allows to create a sparse matrix that we can upload to the GPU. So right now we only support `PRE_FULL_PSI` and `PRE_LIN_PSI`. I yesterday also implemented `PRE_PSI` but I was not too satisfied with it since it was not faster than `PRE_LIN_PSI` and it increased the precomputation time quite a bit. So I may integrate that option but right now I am not completely sure. Accuracy should not be a concern if one choses the LUT large enough.
