### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by iamdiggi** [NFFT/NFFT3#16]
Hello Sir,

I am new to Julia and NFFT so please do not mind if it is a silly question. I am trying to perform a one-dimensional NFFT using NFFT3 in Julia. The issue is I am not able to build Plan for the transformation. Can you help me with the function? I really appreciate any help you can provide.

**Comment by passscoed** [comment]
I'll post sample code showing how to do a one dimensional NFFT using NFFT3.
```
using NFFT3
N      = (20,)
M      = 100
X      = rand(M) .- 0.5
fhat   = rand(N[1]) + im * rand(N[1])
p      = NFFT(N, M)
p.x    = X
p.fhat = fhat
NFFT3.nfft_trafo(p)
f      = p.f
```
When defining `N`, the comma before the closing bracket is really necessary to define a one-dimensional tuple. This could be a possible problem. If it still doesn't work, can you please send the code that causes the error?

**Comment by iamdiggi** [comment]
Thank you very much, It worked!
